version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: dev-dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./dev/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network-johnjlincoln-laravel

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./dev/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network-johnjlincoln-laravel

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: johnjlincoln-laravel
      MYSQL_ROOT_PASSWORD: develop
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata-johnjlincoln-laravel:/var/lib/mysql
      - ./dev/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network-johnjlincoln-laravel

#Docker Networks
networks:
  app-network-johnjlincoln-laravel:
    driver: bridge

#Volumes
volumes:
  dbdata-johnjlincoln-laravel:
    driver: local
